version: 2

updates:
  - allow:
      - dependency-type: "all"
    assignees:
      - "jrauschenbusch"
    commit-message:
      prefix: "chore"
      include: scope
    directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "npm"
    rebase-strategy: auto
    reviewers:
      - "jrauschenbusch"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
